(load "cube.scm")
(load "sum.scm")

(define (simpson-integral f a b n)
  (define h (/ (- b a) n))
  (define (factor k)
    (cond ((or (= k 0) (= k n)) 1)
          ((even? k) 2)
          (else 4)))
  (define (term k)
    (* (factor k) (f (+ a (* k h)))))
  (define (next k) (+ k 1))
  (* (/ h 3) (sum term (exact->inexact 0) next n)))

(simpson-integral cube 0 1 100)
(simpson-integral cube 0 1 1000)
